### ISSUE TITLE
Demo doesn't work on macOS

### ISSUE THREAD

**Issue by RUSshy** [gecko0307/dagon-demo#3]
Hi,

I have macOS 13.3.4 with GPU GTX 960 and demo doesn't work:

```
➜  dagon-demo git:(master) ./dagondemo 
Allocated memory at start: 0
OpenGL version loaded: gl40
Loading scene "TestScene"
Error in fragment shader:
ERROR: 0:18: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:19: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:20: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:21: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:22: Invalid call of undeclared identifier 'texture2D'

Error in fragment shader:
ERROR: 0:18: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:19: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:20: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:21: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:22: Invalid call of undeclared identifier 'texture2D'

Running...
OpenGL error: 1282
Allocated memory at end: 0
```

**Comment by gecko0307** [comment]
https://github.com/gecko0307/dagon/commit/34af9316bf1bceb8ac9a7ec272afc38a1a80c904 should fix this. Does the demo work now?

**Comment by RUSshy** [comment]
Sorry i went sleep few minutes after

I tried now with master i get this:

 ```
Running ./dagondemo 
Allocated memory at start: 0
OpenGL version loaded: gl40
Loading scene "TestScene"
Running...
OpenGL error: 1282
Allocated memory at end: 0
```

The window open, but once loading finish it crash

**Comment by gecko0307** [comment]
I can add [debug output](https://www.khronos.org/opengl/wiki/Debug_Output), but it requires GL 4.3. Is it available on mac? I'm not sure.

**Comment by gecko0307** [comment]
Recently Apple [dropped future support for OpenGL](https://developer.apple.com/macos/whats-new/#deprecationofopenglandopencl) in favour of Metal, so there's no point for me to bother with macOS anymore.

**Comment by RUSshy** [comment]
oh yes i seen that news, this sucks :/  

Why not use bgfx as backend so it can support everything without problem ? https://github.com/bkaradzic/bgfx

**Comment by gecko0307** [comment]
Theoretically it's possible, but it means rewriting nearly the whole stuff (once more, because I've already rewrote it recently for modern OpenGL). I don't know bgfx, so I'll have to learn it first. From what I've learned by a quick API review, it's not clear for me how serious effort it would take. And I won't actually get any benefit from such refactoring other than supporting a platform which I even can't properly test on. 
Finally, IMO, Apple should rethink their policy, not game engine devs. OpenGL was designed as a cross-platform graphics library, and having an additional abstraction layer on top of it (as well as supporting multiple APIs in one application) is a bit pointless for me. Their decision pushes back into 90s when every game engine had to include drivers for each graphics card vendor. Maybe for AAA companies it's not a big deal, but for hobby projects like mine it's barely affordable. Seams like Apple wants to invest less and earn more which they of course have their right to, but we hobby devs also have our right to do things our way. Relying on an open standards like OpenGL was a common practice for years, and it's a platform/hardware vendor's task to provide a standard API. No standard APIs, no cross-platform applications. There's already enough compatibility issues between Windows and Linux to take care about (like window management, threading, fibers, filesystem quieries and such) - at least graphics API has to be a common denominator, or we are going back to 90s. Sure, Windows also has poor native OpenGL support, but at least it doesn't have a problem with third-party drivers.
